### PR TITLE
A few css changes to make the header bigger

### PR DESCRIPTION
**Pull request by heronblade**
### Testing Instructions
1. Pull this branch down into your `plugins` folder.
1. Pull down this [branding plugin branch](https://github.com/5thColumn/kibana5-plugin-5c-branding/tree/make-headers-bigger) specifically the `make-headers-bigger` branch into your `plugins` folder.
1. Add an HTML visualization to a dashboard in your local Kibana, and add the following code
```
<script data-name="myscript">
var thisScript = document.querySelector('script[data-name="myscript"]');
fiveC.header(
'title', 
'https://5thcolulmn.net/cdn/hoops.jpeg',
thisScript);
</script>
```

If everything works correctly, you should see the following.  The image should be nearly all the way across the screen, and around `176px` tall :)

screen shot 2017-03-03 at 4 13 22 pm

This PR address [this](https://github.com/5thColumn/kibana5-plugin-5c-branding/issues/21) issue and [this](https://github.com/5thColumn/kibana5-plugin-5c-branding/issues/20) one

### CODE REVIEW

**Comment by adamyala** [comment]
I can't seem to get this to work. Below is a screen shot of what I'm seeing. The header has a height of 120px.

screen shot 2017-03-06 at 11 14 07 am

Below is a shell script I just wrote to test kibana plugins. It details the exact steps I'm using.

**Comment by csavage1994** [comment]
This worked for me, I got 176 px for the containing div

**Comment by adamyala** [comment]
Our kibana plugin testing process is really horrible right now. I'm going to approve this just so we can continue developing. I'm taking coltons word for it.

**Comment by heronblade** [comment]
I agree @adamyala.  I normally have to go through and change all of my ranches back to `dev` so that I can test any PRs.  Maybe we should just make that standard procedure, and if you are using a different branch on one of the plugins locally, make a note of it in the testing instructions.  Thanks for the thumbs up

**Pull request merged**
